<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>FarmerPortraits</AssemblyName>
    <Version>1.0.0</Version>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ModBuildAlwaysIgnoreSharedGamePath>true</ModBuildAlwaysIgnoreSharedGamePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <RestoreAdditionalProjectSources>https://api.nuget.org/v3/index.json</RestoreAdditionalProjectSources>
  </PropertyGroup>

</Project>
