name: Build Mod

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Decompress Project
      run: unzip FarmerPortraits.zip -d .

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Upload DLL
      uses: actions/upload-artifact@v3
      with:
        name: Mod-Compilado
        path: '**/bin/Release/**/*.dll'
        
